debug = false
disable_crowdin = false
check_for_updates = true

[activations.46927964-3207-377a-84d7-26a82d52be1e]
toggle = false
type = "INHERIT"
[activations.b01b59f4-6556-35a0-9160-e955dc606352]
toggle = true
type = "INHERIT"
[[key_bindings]]
name = "key.plasmovoice.proximity.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 86
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.proximity.distance_increase"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 265
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.proximity.distance_decrease"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 264
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.broadcast.toggle"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 341
type = "KEYSYM"

[[key_bindings.keys]]
code = 61
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.groups.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 3
type = "MOUSE"

[[key_bindings]]
name = "key.plasmovoice.groups.toggle"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 4
type = "MOUSE"

[servers.18c25cbc-6ff0-4fa2-8b0c-513f71e10216.distances]
b883cd09-ef51-3ee0-b72f-28aba1e5c184 = 1024
4aec07ba-d109-3345-9a0a-92022a116cd0 = 4


[voice]
disabled = false
microphone_disabled = false
activation_threshold = -45.0
input_device = "OpenAL Soft on Microphone (HyperX QuadCast 2)"
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 0.6
noise_suppression = false
volume = 2.0
compressor_limiter = true
sound_occlusion = true
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.broadcast]
volume = 0.3
[voice.volumes.source_682a9759-a822-493b-a8da-0dcd0f666929]
volume = 2.0
[voice.volumes.source_1d621ef9-9331-4839-8fce-3593f011e74a]
volume = 2.0
[voice.volumes.source_3d9ba365-03b5-4b17-936c-9577e425ec49]
volume = 2.0
[voice.volumes.groups]
volume = 1.0
[voice.volumes.source_dbc20ff9-5961-45cd-9795-502000288bc4]
volume = 1.05
[voice.volumes.priority]
volume = 1.0
[voice.volumes.source_344ca004-0d26-4ae2-ac7c-a5ffce834909]
volume = 1.5
[voice.volumes.source_29048974-bc9e-46ed-9f44-da1799d7917a]
volume = 2.0
[voice.volumes.source_fe814937-027a-4085-a8e6-6226f17af29f]
volume = 2.0
[voice.volumes.source_1b8ba475-0efb-47dc-9da8-8fe97f02d53b]
volume = 2.0
[voice.volumes.source_08667f96-afc5-4c44-961f-40370accf10b]
volume = 1.2
[voice.volumes.proximity]
volume = 2.0
[voice.volumes.source_336ec677-ae2d-4e06-9455-065f959a57f7]
volume = 1.85
[voice.volumes.whisper]
volume = 1.0

[advanced]
visualize_voice_distance = false
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
mute_player_on_direct = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true
jitter_packet_delay = 3
al_playback_buffers = 5
adaptive_jitter_buffer = false

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
broadcast = "ON"
proximity = "ON"
whisper = "ON"
groups = "WHEN_TALKING"
priority = "ON"
